
 # This YAML configuration file is used to specify parameters and settings for the simulation process
 # of the numerical homogenization of mechanical properties for 2D problems.
 
 # The config file allows the user to change the simulation parameters such as mesh dimensions, material
 # properties, load matrices and has a choice between two different geometries
 
 # Apart from that the user can adjust the directory settings for input/output files,
 # settings for the file with the results and additional settings for the simulation process.

simulation_parameters:
  n: 3  # Amount of regions in a mesh is n^2 => mesh has dimensions n x n
  sample: "chessboard"  # Type of geometry - either "chessboard" or "sandwich"
  Y1: 100  # Young modulus Y1 for region A
  Y2: 50  # Young modulus Y2 for region B
  lc_parameter: 0.16 # parameter for meshing

directories:
  # if the directory does not exist, then it is created
  # if the directory already exists, then all the contents within the directory are deleted beforehand
  # absolute_path_to_dir_with_data should contain the skripts downloaded
  # all other dirs are relative to the absolute path
  absolute_path_to_dir_with_data: "/C/Plocha/Semestral_project/Python_skripts/"
  dir_where_yamls_are_created: "data_vtu/yamls_dir"
  path_to_yaml_template: "data_vtu/TEMPLATE_DO_NOT_DELETE/template.yaml"
  directory_where_vtus_are_created: "data_vtu/vtu_files"
  dir_where_mesh_and_geo_are_created: "data_vtu/"


results_file_settings:
  #the file is always a .txt file so no need for .txt
  name_of_file_with_tensor: "example_tensor"
  # if the output directory for the file with the results does not exist, then it is created
  # if the output directory already exists, then all the contents within the dir are deleted beforehand
  # this dir is relative to the absolute path
  output_dir_of_file_with_tensor: "/results_elastic_tensor"

additional_settings:

  delete_yaml_dir_after_simulation: "no"  # Do you want to delete the YAML directory after simulation?
  delete_vtu_dir_after_simulation: "no"  # Do you want to delete the VTU directory after simulation?

  # Do you want to change the names of the computed YAML files?
  # "yes" - then the yamls are created with the names taken from new_names_of_yamls
  # "no" - default setting of names - results1.yaml, results2.yaml, results3.yaml
  change_names_of_computed_yamls: "no"
  new_names_of_yamls: ["name1.yaml","name2.yaml","name3.yaml"]  # New names for computed YAML files

  # Do you want to change the names of the computed output directories?
  # "yes" - then the output directories are created with the names taken from new_names_of_output_dirs
  # "no" - default setting of names - output1, output2, output3
  change_names_of_computed_output_dirs: "no"
  new_names_of_output_dirs: ["name1","name2","name3"]  # New names for computed output dirs

  # Do you want to change the names of the computed vtu files?
  # "yes" - then the vtu files are created with the names taken from new_names_of_vtu_files
  # "no" - default setting of vtu file names - 1_mechanics-00000.vtu, 2_mechanics-00000.vtu, 3_mechanics-00000.vtu
  change_names_of_computed_vtu_files: "no"
  new_names_of_vtu_files: [ "name1.vtu","name2.vtu","name3.vtu" ]  # New names for computed output dirs

  # Do you want to change the name of the generated mesh file?
  # "yes" - then the mesh file is created with the name taken from new_name_of_mesh
  # "no" - default setting of mesh file is given - generated_mesh.msh
  change_name_of_msh_file: "yes"
  new_name_of_mesh: "example.msh"

  # Do you want to create a .geo file with the geometry (points, lines, surfaces, phys. groups)?
  create_geo_file: "yes"

  # if you chose "yes" to create geo file, then this is relevant, otherwise not:
  # Do you want to change the name of the generated mesh file?
  # "yes" - then the geo file is created with the name taken from new_name_of_geo
  # "no" - default setting of mesh file is given - generated_geo.geo_unrolled
  change_name_of_geo_file: "yes"
  new_name_of_geo: "example.geo_unrolled"

  # Do you want to measure the time it took to do the computation?
  measure_time_of_computation: "yes"